### ISSUE TITLE
SVG rendering issue

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/balancing-act#147]
When I export an image as an svg, I can confirm in illustrator that it looks reasonable (when I open the exported svg). 
![image](https://github.com/phetsims/balancing-act/assets/7852916/e4472fbc-0d12-4547-942f-2f62cca44330)

When I use "preview" (space bar, on a mac) I can see that there are gaps between the color regions. 
![image](https://github.com/phetsims/balancing-act/assets/7852916/101b5137-fdfa-4a41-a539-bb248e58a0ad)

When the image is rendered in the browser there are also gaps (they look like white lines between the different green shades). 
![image](https://github.com/phetsims/balancing-act/assets/7852916/b1a49367-7768-4cbf-a6e0-247004b4d50b)

We experimented with different export settings but they don't seem to be helping. We also tried using a .5px stroke around the regions and that didn't seem to fix it either. 

If I add a background layer that is filled with the dark green area, this seems resolved, but we didn't try it in the sim. We suspected this would help, but most artwork will need to be redrawn, and it will likely be slightly more expensive for our artist to draw all artwork in this way, but is do-able. 
![image](https://github.com/phetsims/balancing-act/assets/7852916/5cc4d894-f8b2-4e35-9bec-d02e1aadd703)

@marlitas is going to share some relevant info below that may also be helpful.

**Comment by marlitas** [comment]
So from the initial research I did it looks like this is an SVG renderer problem with [conflation artifacts and anti-aliasing ](https://graphicdesign.stackexchange.com/questions/65058/image-looks-embossed-when-converted-to-svg). 

@amanda-phet's solution will work, but based on the comments in this[ thread ](https://graphicdesign.stackexchange.com/questions/73601/is-there-a-reason-hillary-clintons-logo-has-hidden-notches)it seems some of the alpenglow work will also help with this. Perhaps we still need to move forward with Mariah redrawing for Balancing Act since I believe Alpenglow is not at a stage that it can help us with this quite yet? But correct me if I'm wrong @jonathanolson.

**Comment by amanda-phet** [comment]
The thread @marlitas linked to might not be the right one. This is the thread we were looking at : https://graphicdesign.stackexchange.com/questions/93984/exporting-to-svg-leaving-ghost-path-lines 

The artwork for this sim doesn't need to be redrawn. I took the route explored above and created background fills for most shapes that could work for. I did a more detailed modification of the rainbow present, but it wasn't too hard. On my computer, when I see the artwork rendered, it is looking ok to my eye. So I'm going to upload new artwork, and hopefully it works!

**Comment by amanda-phet** [comment]
I've uploaded new artwork and so far it look promising. Over to @Luisav1

**Comment by Luisav1** [comment]
This issue was fixed with a new technique @amanda-phet found and it hasn't reappeared on the images since. Closing.

**Comment by amanda-phet** [comment]
Thanks. The bucket also needs fixing, so I'll just go ahead and redo all of the level icons with the correct artwork. 
![image](https://github.com/phetsims/balancing-act/assets/7852916/014b3dff-f4e0-4814-8bb9-6f7966b36c20)

**Comment by amanda-phet** [comment]
I'm struggling to export these without issues while keeping their file sizes small. The bucket is the main one I can find an issue with. The others might be fine exporting at the lower decimal (but that's what can cause strange waves and artifacts). 

The only idea I have for keeping these small is to draw them in code. Does that sound feasible?

**Comment by amanda-phet** [comment]
I uploaded the best I think I can do right now... please see how those 4 new icons look!

**Comment by amanda-phet** [comment]
In the process I also updated the barrel and the dog. I'm not seeing a noticeable difference for the dog, but the barrel is a lot smaller.

**Comment by Luisav1** [comment]
Adding the background and plank elements was straightforward - though they might need some tweaking for size and other details. But getting adding the masses requires changing the existing code since the model masses aren't easily accessible, yet they are essential for creating the node masses. While it's feasible to generate these images in the code, it does require changing it up a bit. Not sure which way to go from here.
![image](https://github.com/phetsims/balancing-act/assets/52978048/d80d47be-c74d-4f7e-ba64-58ecb09dcd29)

**Comment by amanda-phet** [comment]
We could replace level 2 and 3 with these icons, which are larger file sizes but don't have the gaps. I'll let you decide which path to take, I'm ok either way. 

![gameLevel3Icon](https://github.com/phetsims/balancing-act/assets/7852916/5f5c4eb6-cca2-400c-b7ab-bfc5c4e71f36)
![gameLevel2Icon](https://github.com/phetsims/balancing-act/assets/7852916/051ac0b7-44b4-4a61-929c-db87a7ce70c7)

**Comment by Luisav1** [comment]
Hm, I think we should opt for those larger images that don’t have those SVG rendering issues to maintain consistency. However, I wonder if it’s possible to compress them. I’m not entirely sure about the process, as I know we can’t make them smaller directly. Do you know @amanda-phet? Otherwise, if not possible, I'm okay with them having larger file sizes!

**Comment by amanda-phet** [comment]
OK let's just use the larger ones that are in my comment above. One of them was comparable and not a huge jump in size. 

I tried using svgoptimizer.com, and it didn't reduce the file size at all. I remember Marla tried it out as well (maybe the same site or similar) and didn't see huge noticeable improvements, so at this point I don't want to investigate any more time into this.

**Comment by Luisav1** [comment]
The larger images are looking good and without issues! 
![image](https://github.com/phetsims/balancing-act/assets/52978048/ae3ab111-555c-4167-8849-8502fd077e90)

Closing.
