### ISSUE TITLE
Position Panel can be cut off with ?stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balancing-act#157]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1073, on the Game Screen with ?stringTest=dynamic, the Position Panel gets cut off with smaller window sizes.

**Steps to reproduce**
1. Add ?stringTest=dynamic to the end of the url
2. Select any level on the game screen
3. Press the right arrow key 3 times
4. Grab the right side of the window and make it smaller

**Visuals**
<img width="399" alt="Screenshot 2024-04-22 at 9 13 25 PM" src="https://github.com/phetsims/balancing-act/assets/87318828/2e488e17-ec0e-4905-90ca-6494a4e9bcfb">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Balancing Act‬
URL: https://phet-dev.colorado.edu/html/balancing-act/1.3.0-dev.1/phet/balancing-act_all_phet.html?stringTest=dynamic
Version: 1.3.0-dev.1 2024-04-22 16:12:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15
Language: en-US
Window: 1317x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
This can also be seen in a number of languages in the options dialog

**Comment by Luisav1** [comment]
I added a listener that updates the position of the `PositionIndicatorControlPanel` to always be 10 pixels away from the right edge of the layout bounds whenever the string properties change, so the panel appears to stretch towards the left for longer strings. This behaviour was not happening in the other screens with the `PositionIndicatorControlPanel` because the panel's min and max width are set to the same value.

This is now fixed as seen below:
![image](https://github.com/phetsims/balancing-act/assets/52978048/99750786-52ee-4d47-9d5d-228a862a7b0f)
Closing.
