### ISSUE TITLE
dragListeners should be interrupted with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balancing-act#158]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.4.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1073, on the Intro screen if I am holding an object with one finger and I press Reset All with another, the dragListener isn't interrupted. 
On the Balancing Lab screen, if I do the same thing, the object is returned to the carousel but the white indicator on the balance is still there and will move around with my finger. After I lift my finger the white indicator remains, even after pressing Reset All. 

**Steps to reproduce**

On the Intro Screen:
1. Grab any object and hold with one finger
2. Press Reset All with another finger.

On the Balancing Lab Screen:
1. Grab an object and hold it above the balance with one finger
2. Press Reset All with another finger
3. Continue to move the now invisible object around with the first finger and then let go
4. Press Reset All again

**Visuals**

https://github.com/phetsims/balancing-act/assets/87318828/068e2f4c-c3a2-473b-b3b5-2c2e3e21ef04

https://github.com/phetsims/balancing-act/assets/87318828/b3ef0003-d044-4869-acf4-b86175270cf4

**Comment by Luisav1** [comment]
The issue was that during a reset, previously `Mass.dispose()` unlinked all listeners on `userControlledProperty`, including  `userControlledMassesUpdater` which indirectly updates `activeDropPositions`, crucial for correctly showing the plank highlights. To update the highlights, `userControlledProperty` needed to be reset. But directly resetting the property wasn't feasible due to listener order dependency. (Resetting the property before unlinking other listeners caused incorrect mass additions to the plank.)

My workaround was to unlink all listeners, relink only `userControlledMassesUpdater`, resetting `userControlledProperty` to correct the highlights, and then unlink that listener, making the new `dispose()` function:
```js
 dispose() {
    this.userControlledProperty.unlinkAll();
    this.userControlledProperty.link( this.userControlledMassesUpdater );
    this.userControlledProperty.reset();
    this.userControlledProperty.unlink( this.userControlledMassesUpdater );
    super.dispose();
  }
```
Additionally, since `userControlledMassesUpdater` adds masses to `userControlledMasses`, it was modified to prevent duplicate entries due to the unlinking / relinking.

This fixes the highlight issue in the Balance Lab screen. I still need to look more into the Intro screen issue.

**Comment by Luisav1** [comment]
In the Intro screen issue, resetting the `userControlledProperty` removed the plank highlights for the mass, but the active `dragHandler` caused the mass to go back to its previous position. So, interrupting the `dragHandler` was simpler. This fix also works for the Balance Lab screen.

I've added an emitter that interrupts the `dragHandler` when the reset button is pressed. The `interruptlistener` on the `interruptDragHandlerEmitter`, triggered by the reset button, interrupts the `dragHandler` on the `massNode`. This listener is removed from the emitter when the mass is removed from `massList`.

This issue is now fixed. Closing.
