### ISSUE TITLE
Font "strobes" when plank is in motion

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balancing-act#16]
Fonts forthe mass labels, ruler, and marks all seems to flutter/strobe when the plank is in motion. Not a critical issue.

I see the behavior in Chrome and Firefox. On all 3 screens. But do NOT see the issue in IE (version 11.0.9600.16521)

**Comment by samreid** [comment]
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by samreid** [comment]
The TODO is not related to this issue, closing.

**Comment by samreid** [comment]
> The TODO is not related to this issue, closing.

Upon review, it seems the TODOs are related to this issue.  @jbphet do we still need the RasterizedTextNode workaround?

**Comment by jbphet** [comment]
I've removed the `RasterizedTextNode` workaround, tested a bit locally, and have enlisted the help of the QA team to test on all supported platforms, see https://github.com/phetsims/qa/issues/686.  I'll defer this issue until I hear back from QA.

**Comment by jbphet** [comment]
I had QA test the master version with the "rasterized text" workaround removed, and it seems like the problem with strobing and aliasing still exists.  I'm not going to revert my changes just yet though.  Instead, I'll mark this issue as deferred, and the next time this sim is published from master we should take a little more time to re-evaluate and decide if we should revert the changes (and thus go back to using rasterized text), or leave them in place because the aliasing/strobing isn't as bad as it once was.  Browsers may have gotten better at handling rotating text by then.

**Comment by marlitas** [comment]
I'll take a look at the changes here and check in if this problem is still occurring.

**Comment by AgustinVallejo** [comment]
I tested in Chrome and Firefox and couldn't notice any strobing, even zoomed in and lowered the sim's speed, and it seems smooth. Should this issue be closed? @marlitas

**Comment by marlitas** [comment]
I think if you tested and couldn't find it we can probably close. QA can re-open or create a new issue if it starts happening again. Thanks!
