### ISSUE TITLE
Randomness of game objects

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#164]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1084
I noticed that some of the objects in the game screen didn't seem to show up when I was playing. Such as the dog pictured on the level 4 icon. I may have been unlucky/not looked enough, but it may be worth it to look at the randomness of those objects.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Balancing Act‬
URL: https://phet-dev.colorado.edu/html/balancing-act/1.3.0-rc.1/phet/balancing-act_all_phet.html
Version: 1.3.0-rc.1 2024-05-02 23:09:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language: en-US
Window: 1280x631
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
In the `BalanceGameChallengeFactory`, all masses are selected randomly using the `randInt` function to obtain a random index from the mass list.

However, there are a few reasons why some objects like the puppy might seem to appear less frequently:
1. **Easier challenges**, especially more in levels 1 and 2, tend to use more of the brick stacks.
2. **Tilt challenges** don't use the following objects due to layout constraints (taller masses end up going behind the tilt prediction selector): BigRock, Boy, Girl, Man, Woman, Barrel, Puppy, SodaBottle.
3. The list of available fixed masses (not a mystery mass) contains a significant number of brick stacks and rocks, which could explain why they appear more often:

```js
const BALANCE_CHALLENGE_MASSES = [
  new BrickStack( 1, Vector2.ZERO ),
  new BrickStack( 2, Vector2.ZERO ),
  new BrickStack( 3, Vector2.ZERO ),
  new BrickStack( 4, Vector2.ZERO ),
  new TinyRock( Vector2.ZERO, false ),
  new SmallRock( Vector2.ZERO, false ),
  new MediumRock( Vector2.ZERO, false ),
  new BigRock( Vector2.ZERO, false ),
  new Boy( Vector2.ZERO, false ),
  new Girl( Vector2.ZERO, false ),
  new Man( Vector2.ZERO, false ),
  new Woman( Vector2.ZERO, false ),
  new Barrel( Vector2.ZERO, false ),
  new CinderBlock( Vector2.ZERO, false ),
  new Puppy( Vector2.ZERO, false ),
  new SodaBottle( Vector2.ZERO, false ),
  new SmallBucket( Vector2.ZERO, false )
];
```

Based on what I found, I think this issue could be closed but I'm passing it back to QA to decide.

**Comment by KatieWoe** [comment]
Closing
