### ISSUE TITLE
fuzzMouse Behavior: Caught Objects Don't Stop

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balancing-act#43]
In the Balancing Lab screen, normally releasing an object would start the flying animation back to the carousel. But if the object is caught in mid air before it can reach the carousel, the object continues to fly and never stops (fig. 1). I first noticed this while testing with "fuzzMouse", along with two other issues. This is the only issue I was able to reproduce, while the others may be humanly impossible (unless someone is a really fast clicker). The other two seen on this screen were objects flying away from the carousel like flying down or to the left (fig. 2), and force arrows with no objects above them (fig. 3), but these again were un-reproducable.

fig. 1:
![balaac](https://cloud.githubusercontent.com/assets/5863899/6047098/c1dce8c2-ac64-11e4-8db8-94b826ab67e2.gif)

fig. 2:
![wrong way flying 2](https://cloud.githubusercontent.com/assets/5863899/6048237/21d28d84-ac6c-11e4-9452-532b3ceb8ff2.gif)

fig. 3:
It's still tilted as if an object is there weighing it down.
![ghost man](https://cloud.githubusercontent.com/assets/5863899/6047566/bc5cbaa0-ac67-11e4-9138-f06a54561258.png)

Seen in Win 8.1 and OSX 10.9.5 browsers.

Troubleshooting information:
Name: Balancing Act
URL: http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.0.2/balancing-act_en.html
Version: 1.0.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by phet-steele** [comment]
@oliver-phet discovered that occasionally after grabbing something mid-flight (fig. 1 issue) the user may have control over the object and be able to place an invisible one on the see-saw (fig. 3 issue). Clicking reset all was also found to reset everything correctly except that the little white dashes on the see-saw that light up when an object is hovered over them don't reset correctly. The sim still shows as if something is on the see-saw when in reality there isn't.

**Comment by jbphet** [comment]
I tried to duplicate this while fixing issues in preparation for the 1.1 release (which is being done to add translatability), and was unable to make it happen.  This should be retested on the first 1.1 release candidate.

**Comment by phet-steele** [comment]
@jbphet yep, still happens in 1.1.0-rc.1

**Comment by ariel-phet** [comment]
Looks like this was reported "in the wild"

https://twitter.com/mevr_verstappen/status/913816774981939200

**Comment by KatieWoe** [comment]
Reported in the wild again. This time in an email in phethelp:
![image](https://user-images.githubusercontent.com/41024075/70814748-5e6abd00-1d89-11ea-861b-5c84fe656591.png)

**Comment by jbphet** [comment]
Since it's been seen a couple of times by our users, I decided to take the time to investigate and fix.  The problem is that it's possible to grab the objects with a touch swipe while they are animating back to the carousel, which causes a number of problems, such as setting up another animation on the same object when it is released again.  I've added code to set the node's `pickable` attribute to `false` during animations, and that seems to prevent the problem from arising.

For reference, the problem could be reproduced fairly easily on a touch device by grabbing objects off of the carousel, dragging them to the upper left - beyond the left edge of the balance - letting it go and then swipe-dragging over it several times as it tried to make its way back to the carousel.  After doing this a few times, and then doing normal drags of objects from the carousel onto the balance, weird things start happening, such as objects popping into existing near the balance.

An RC with the fix is available at https://phet-dev.colorado.edu/html/balancing-act/1.1.24-rc.1/balancing-act_en.html.  I discussed this with @KatieWoe, and she's willing to take this from here, and do an RC spot check.  @KatieWoe - if the problem appears to be fixed and nothing new introduced, let me know and I'll publish.

**Comment by jbphet** [comment]
@KatieWoe - Please have QA check to see if this is resolved on master.  If the issue is no longer reproducible, please close.  If something that is perhaps related but not the same, such as a multi-touch issue, please open a new one rather than continue the conversation here.

**Comment by KatieWoe** [comment]
I wasn't able to reproduce on master
