### ISSUE TITLE
The PNG images should be optimized

### ISSUE THREAD

**Issue by kelson42** [phetsims/balancing-act#46]
Having smaller image files allows a faster loading and a better user experience.
It's possible to optimize the pictures without any quality loss.
I have tried with trimage on all PNG files and won ~25% of size/bandwidth.

**Comment by ariel-phet** [comment]
@kelson42 - can you give a little more background as to how you are using this simulation? Have you made your own working copy? And can you elaborate on which platform you are seeing a suboptimal user experience?

**Comment by kelson42** [comment]
@ariel-phet I'm mostly interested to store Phets locally, that why I'm having a look pretty carefully to the storage usage. But, I want to serve it too, through a web serviice, and then of course everything should be done to keep pages small - so even users with low bandwidth can access the content in the best conditions.

**Comment by samreid** [comment]
Just sleuthing around to get more context.  @kelson42's profile links to this project page http://www.kiwix.org/wiki/Main_Page which says:

> Kiwix enables you to have the whole Wikipedia at hand wherever you go! On a boat, in the middle of nowhere or in Jail, Kiwix gives you access to the whole human knowledge. You don't need Internet, everything is stored on your computer, USB flash drive or DVD!

**Comment by marlitas** [comment]
We can look at optiziming png sizes when we export the new artwork in. File size has been a recent concern for the region and culture work, so this issue fits right in there. Assigning to me and @amanda-phet so we can strategize what might be the best options for this sim.

**Comment by Luisav1** [comment]
@amanda-phet's investigation found that while certain artwork files, such as those depicting people, could be downsized, others, like the `barrel`, had limitations. Despite optimization efforts, the file size increased slightly to cover [all the new regions](https://github.com/phetsims/balancing-act/issues/140). Some reduction was achieved on objects like the `flowerPot`, but further size reduction is unlikely to be significant since the files are already small. Thus, the issue will be closed. Thanks to @amanda-phet for the investigation!
