### ISSUE TITLE
Delete blue bucket

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#54]
https://github.com/phetsims/chipper/issues/189 reports that blue-bucket.png is unused.  Can we delete it and its related files?

* SmallBucket.js
* blue-bucket.png
* blue-bucket.ai

**Comment by jbphet** [comment]
The blue bucket was removed from the list of masses used in the mass deduction challenges a while back because its mass would necessitate the use of decimal values in the mass entry dialog, and the HTML5 version of this sim doesn't support entry of values with decimals.  I decided to try adding the blue bucket to the list of masses that can be used in tip-predication and balance challenges, and it appears to work great.  So, rather than delete it, I'm adding it to some of the other challenge types.

**Comment by jbphet** [comment]
Issue addressed, closing.
