### ISSUE TITLE
User reported odd bug with characters "appearing out of nowhere"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balancing-act#82]
@phet-steele see this tweet https://twitter.com/mevr_verstappen/status/913816774981939200

Not sure if this is reproducible or not, sounds like on iOS10 still. Not sure if this is something odd related to the app or what, but I have never seen such behavior.

**Comment by phet-steele** [comment]
@ariel-phet please see #43. Specifically the first post and this sentence in https://github.com/phetsims/balancing-act/issues/43#issuecomment-72937339:

> ...after grabbing something mid-flight (fig. 1 issue) the user may have control over the object and be able to place an invisible one on the see-saw (fig. 3 issue).

Once this is triggered, placing a new object on the beam will cause the invisible objects to fly back (but only visually). You can tell in the video that they have invisible objects since the presented situation is unphysical otherwise (they have 2 invisible men and one invisible woman).

@ariel-phet I'd advise to close this as a duplicate and continue in #43. I have good confidence that the user report is that issue (or at least would be solved by fixing that issue).

> Not sure if this is something odd related to the app or what

Not app specific, but certainly easier to do on a touch screen.

**Comment by ariel-phet** [comment]
Closing since likely a duplicate issue
