### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#87]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Pointer Areas of bricks in tool box appear even when not in tool box.  Clicking/dragging them does not seem to do anything

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56324294-b8987d00-612b-11e9-8ed1-b74e88241026.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56324296-b8987d00-612b-11e9-9da3-8a2e58c895e3.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56324297-b8987d00-612b-11e9-8934-d41b6c3d1d3b.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/41024075/56324298-b9311380-612b-11e9-9593-59e257b1dba7.png)
![Image from iOS (5)](https://user-images.githubusercontent.com/41024075/56324299-b9311380-612b-11e9-98ba-9bb3a980a08d.png)
![Image from iOS (6)](https://user-images.githubusercontent.com/41024075/56324300-b9311380-612b-11e9-80e5-41e320355915.png)
![Image from iOS (7)](https://user-images.githubusercontent.com/41024075/56324301-b9311380-612b-11e9-93bb-758f1d487464.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56324302-b9311380-612b-11e9-92a4-8cd3bf6f1915.png)

**Comment by arouinfar** [comment]
Thanks @KatieWoe. 

This looks similar to the carousel in CCK, see https://github.com/phetsims/circuit-construction-kit-dc/issues/178. @jbphet can you look into this?

**Comment by SaurabhTotey** [comment]
Looking at the code, it looks like the container used in this simulation is a KitSelectionNode common-code component. Similarly to Carousel, it looks like KitSelectionNode uses clip areas. As such, I believe this issue is almost exactly the same as https://github.com/phetsims/circuit-construction-kit-dc/issues/178. The brick stacks are getting clipped out, but their pointer areas are still getting shown, even though they aren't actually really touchable while clipped out. I believe this issue can consequently be closed, as that is the action that was taken for https://github.com/phetsims/circuit-construction-kit-dc/issues/178. Assigning to @KatieWoe to review.

**Comment by KatieWoe** [comment]
Agreed
